### ISSUE TITLE
Shape name is changed while converting PPT to PPTX

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#183] opened 2022-03-01 03:44 UTC
#166
Unfortunately,the issue has not been fixed. Sometimes,Shape name is still changed while converting PPT to PPTX .May be it is related to file.
[Uploading test.zip…]()
![image](https://user-images.githubusercontent.com/49870259/156100836-f76a91dd-34c1-4d4b-b0fb-4850b19ffe14.png)

**Comment by andreypotapovaspose** [comment] 2022-03-01 08:56
@MiniCassie,
Thank you for reporting the issue.

I've tested the issue #166.  it has been already fixed in Aspose.Slides 22.2 for that presentation file. Unfortunately, I was unable to download your _Uploading test.zip_ file here. Please share a link to the presentation example. It would be great if you could use our [forum for Aspose.Slides](https://forum.aspose.com/c/slides/) products.

**Comment by MiniCassie** [comment] 2022-03-01 08:58
[test.zip](https://github.com/aspose-free-consulting/projects/files/8160215/test.zip)

**Comment by andreypotapovaspose** [comment] 2022-03-01 09:36
@MiniCassie,
Thank you for the presentation example. I've reproduced the problem with changing the shape names and added a ticket with ID **SLIDESNET-43094** to our issue tracking system. We apologize for any inconvenience. Our development team will also investigate this case. You will be notified when the issue is resolved.

**Closed** 2022-03-31 05:10 UTC

**Comment by andreypotapovaspose** [comment] 2022-04-15 15:13
@MiniCassie,
The issues you have found earlier (filed as SLIDESNET-43094) have been fixed in Aspose.Slides for .NET 22.4 ([ZIP](https://downloads.aspose.com/slides/net/new-releases/aspose.slides-for-.net-22.4(dlls-only)/), [MSI](https://downloads.aspose.com/slides/net/new-releases/aspose.slides-for-.net-22.4/)).
You can check all fixes on the [Release Notes](https://docs.aspose.com/slides/net/aspose-slides-for-net-22-4-release-notes/) page.
You can also find the latest version of our library on the [Product Download](https://downloads.aspose.com/slides/net) page.
