### ISSUE TITLE
I want to convert .docx to pdf

### ISSUE THREAD

**Issue by PH8919** [aspose-free-consulting/projects#326] opened 2023-07-07 03:34 UTC
Please check if it satisfies the following requirements: 
Hi
I'm evaluating your product and want to convert my .docx to .pdf in Linux system. and I used your free trial version in Python as described in [https://pypi.org/project/aspose-words/](url) as follows:

import apose.words as aw
doc = aw.Document("my.docx")
doc.save("my.pdf")

Then I found there are  several mismatchs though it is truncated.
1. the text frame in content is to a new page.
2. chinese isn't supported.
3. the middle dot or align dot is to middle square
4. new blank page follows the TOC

Operation System: **Linux**
Language: **Python**
Python Version:**3.8.3**

Sorry that I can't upload the related docx and pdf due to some factors.

**Comment by AlexNosk** [comment] 2023-07-07 04:41
@PH8919 Please note, to accurately render MS Word documents to PDF, the fonts used in the original document should be available in the environment where the document is converted to PDF. If Aspose.Words cannot find the font used in the original document, the [font is substituted](https://docs.aspose.com/words/python-net/manipulating-and-substitution-truetype-fonts/). This might lead to layout mismatch due to the different font metrics. Also, this might cause incorrect rendering of the characters, like in your case.
Unfortunately, it is difficult to say for sure what the problems are without a real document. You can post your questing in [Aspose.Words support forum](https://forum.aspose.com/c/words/8). It is safe to attach documents in the support forum, since only topic starter and Aspose staff can see the attachments.
I believe, after providing the required fonts, all the described problems will gone. Please see our documentation to learn where Aspose.Words looks for fonts and how to install fonts on Linux:
<https://docs.aspose.com/words/python-net/installing-truetype-fonts-on-linux/>
<https://docs.aspose.com/words/python-net/specifying-truetype-fonts-location/>

**Comment by PH8919** [comment] 2023-07-07 05:15
@AlexNosk
Thanks for your reply.
I will try to install the fonts on my linux and check whether it works well.

BTW, I have another two scenario:
1. Update TOC in my docx and generate it correctly in pdf.
2. Fix the 1st-level chapter number, like "right click on the chapter number -> set numbering value" in MS Office, then the chapter numbe can be fixed.

Thanks again!

**Comment by AlexNosk** [comment] 2023-07-07 06:22
@PH8919 
1. Please see the following article to learn how to work with TOC using Aspose.Words:
<https://docs.aspose.com/words/python-net/working-with-table-of-contents/>
But note, to update TOC Aspose.Words need to build document layout and the fonts are required for this (See my previous answer)
2. You mean this menu in MS Word:
![image](https://github.com/aspose-free-consulting/projects/assets/31235892/25acde1f-207c-441d-aacc-4fef96ec9e18)
You can specify this value using [ListLevel.start_at](https://reference.aspose.com/words/python-net/aspose.words.lists/listlevel/start_at/) property.
But if you need to replace list numbering with static text, then you can using [Document.update_list_labels](https://reference.aspose.com/words/python-net/aspose.words/document/update_list_labels/) method and then access the calculated list label using [Paragraph.list_label](https://reference.aspose.com/words/python-net/aspose.words/paragraph/list_label/) property. For example the following simple code replaces list label of the paragraph with a static text:
```py
doc = aw.Document("C:\\Temp\\in.docx")

# Update list labels.
doc.update_list_labels()

# Get paragraphs where list label must be converted to static text. For demonstration purposes use the first paragraph.
paragraph = doc.first_section.body.first_paragraph

# Convert list item into regular paragraphs with leading text that imitates numbering.
label = paragraph.list_label.label_string + "\t"
fake_list_label_run = aw.Run(doc, label)
paragraph.list_format.remove_numbers()
paragraph.prepend_child(fake_list_label_run)

doc.save("C:\\Temp\\out.docx")
```

**Comment by PH8919** [comment] 2023-07-07 08:19
@AlexNosk

Could your provide an email address? I think I may share my sample with you by email.
For 2, I only want to change the 1st level chapter number of my document so that its sub-level number and other field linked to the 1st level number can change automatically, like the function you show in MS office.  For example:
1  --- 1st level
 1.1
 1.2
Change the 1st level number to 7,  then it will be:
7 --- 1st level
 7.1
 7.2

Thanks

**Comment by AlexNosk** [comment] 2023-07-07 09:51
@PH8919 

1. Unfortunately, we do not communicate in support via e-mail. The main place for getting support is [Aspose.Words support forum](https://forum.aspose.com/c/words/8). The files attached in the forum are safe and are not visible to other users.

2. In this case, the [ListLevel.start_at](https://reference.aspose.com/words/python-net/aspose.words.lists/listlevel/start_at/) property is just what you need.

3. You can configure this using [OutliOptions](https://reference.aspose.com/words/python-net/aspose.words.saving/outlineoptions/) class. In your case it is required to specify [default_bookmarks_outline_level](https://reference.aspose.com/words/python-net/aspose.words.saving/outlineoptions/default_bookmarks_outline_level/) or [bookmarks_outline_levels](https://reference.aspose.com/words/python-net/aspose.words.saving/outlineoptions/bookmarks_outline_levels/).

**Comment by PH8919** [comment] 2023-07-08 06:17
@AlexNosk

For No. 2, you mentioned [ListLevel.start_at](https://reference.aspose.com/words/python-net/aspose.words.lists/listlevel/start_at/)
,I can't run it well, could you provide a exmaple?

My scenario is I have a formal document from MS office with chapters like:
//Here may be some information before the 1st chapter.
1   ---- 1st level chapter
    1.1
    1.2
2   ---- 1st level chapter
    2.1
    2.2
I want to use aw to change chapter number to(1->3, 2->8):
//Here may be some information before the 1st chapter.
3   ---- 1st level chapter
    3.1
    3.2
8   ---- 1st level chapter
    8.1
    8.2

Thanks

**Comment by AlexNosk** [comment] 2023-07-08 13:52
@PH8919 
1. You should specify start at value of the list item paragraph. For example see the following code:
```py
doc = aw.Document("C:\\Temp\\in.docx")

# Get paragraphs where start at value should be chnaged.
paragraph = doc.first_section.body.first_paragraph

# Change start at
paragraph.list_format.list_level.start_at = 3

doc.save("C:\\Temp\\out.docx")
```
[in.docx](https://github.com/aspose-free-consulting/projects/files/11990780/in.docx)
[out.docx](https://github.com/aspose-free-consulting/projects/files/11990781/out.docx)

2. You should specify [ImportFormatOptions.keep_source_numbering](https://reference.aspose.com/words/python-net/aspose.words/importformatoptions/keep_source_numbering/) option to preserve original numbering upon merging documents.

3. Yes, you can package Aspose.Words using Pyinstaller. The following might be useful for you:
<https://stackoverflow.com/questions/74477544/one-or-more-errors-occurred-while-loading-the-module-aspose-word-1009>

**Comment by PH8919** [comment] 2023-07-10 05:02
@AlexNosk

2. I tried your suggestion, the chapter number can be kept. But it cause some errors in the combined document:
A. the field of the chapter number and chapter title in header appears as"Error! No text of specified style in document.
". 
B. my page number includes chapter number ,like "${chapter_number}-${page_number}", and page number starts from 1 in each chapter. After merging, the chapter nubmer is lost.


Thanks.

**Comment by AlexNosk** [comment] 2023-07-10 14:22
@PH8919 Could you please attach your source documents, the problematic output document and the expected output (created in MS Word) along with sample code that will allow us to reproduce the problem? We will check the scenario and provide you more information.

**Comment by PH8919** [comment] 2023-07-11 07:22
@AlexNosk
I consult security members and I'm forbbiden to upload any docx to outside website. I will try my best to describe my issue.
In my document, I insert the cross reference of "chapter number" and "chapter title" in the header so that when the chapter number and chapter title change, the corresponding value in header will change automatically.
and in footer, I set the chapter-based page number style by "page number->set page number style -> inlude chapter number".


my code is:

import_options = aw.ImportFormatOptions()
import_options.ignore_header_footer = False
import_options.keep_source_numbering = True
d1=aw.Document("d1.docx")
d2=aw.Document("d2.docx")
t=aw.Document()
t.remove_all_children()
t.append_document(d1, aw.ImportFormatMode.KEEP_SOURCE_FORMATTING, import_options)
t.append_document(d2, aw.ImportFormatMode.KEEP_SOURCE_FORMATTING, import_options)
t.save("t.docx")


When I open t.docx, 
1. there is an error "Error! No text of specified style in document" at the postion of chapter number and chapter title in header 
2. The only page number is kept, there is no chapter number information for the page number in footer.

Hope this will be helpful for you to reproduce my scenario.

Thanks.

**Comment by PH8919** [comment] 2023-07-11 11:22
@AlexNosk
Unfortunately, when I change  aw.ImportFormatMode.KEEP_SOURCE_FORMATTING to aw.ImportFormatMode.USE_DESTINATION_STYLE, the chapter number become continuous.

and I'm forbidden to upload any document to web site.
Could you follow my previous illustration to make two document, like
1.docx: fix it chapter number 5 with style of Heading 1, add cross reference of chapter number, chapter title in header and chapter-based page number in footer.
2.docx: fix it chapter number 10 with style of Heading 1, add cross reference of chapter number, chapter title in header and chapter-based page number in footer.

then you can share you code and documents to me.

Thanks.

**Comment by PH8919** [comment] 2023-07-13 02:36
@AlexNosk
Could you try it and we are waiting for the conclusion to make final decision.

**Comment by AlexNosk** [comment] 2023-07-13 03:58
@PH8919 With the latest 23.7 version you can use [Merger](https://reference.aspose.com/words/python-net/aspose.words.lowcode/merger/) class to merge document with one line of code:
```py
aw.lowcode.Merger.merge("C:\\Temp\\out.docx", ["C:\\Temp\\in1.docx", "C:\\Temp\\in2.docx"], aw.SaveFormat.DOCX, aw.lowcode.MergeFormatMode.KEEP_SOURCE_LAYOUT)
```
[in1.docx](https://github.com/aspose-free-consulting/projects/files/12035212/in1.docx)
[in2.docx](https://github.com/aspose-free-consulting/projects/files/12035214/in2.docx)
[out.docx](https://github.com/aspose-free-consulting/projects/files/12035215/out.docx)

**Comment by PH8919** [comment] 2023-07-13 08:59
@AlexNosk
I used your solution, the chapter number can be fixed. but the related field in header and footer can't be updated. 

You can insert field related to chapter number in header and chapter-based page number in footer.
1. Insert chapter number field in header by "Insert->Cross-reference->Numbered Item->Paragraph number"
2. Include chapter number in page number in footer by "Page Number->Format Page Numbers->include chapter number"

After above operation to your docx(in1.docx and in2.docx), then you can use your code to verify it.

Thanks.

**Comment by PH8919** [comment] 2023-07-15 09:24
@AlexNosk

I tried your method. it can't work on my template. after merging, the chapter number and title in header can't match its chapter and the chapter number in page number also can't match.

Could you follow [my step](https://github.com/aspose-free-consulting/projects/issues/326#issuecomment-1633844870) to make two docx and merge them into one?

Thanks.

**Comment by AlexNosk** [comment] 2023-07-16 05:30
@PH8919 It would be much easier if you create a sample documents and attach them here for testing along with your expected result.

**Comment by PH8919** [comment] 2023-07-16 13:09
@AlexNosk 
I made two sample documents, you can try with them. I want the in2.docx can be appended to in1.docx. At the same time, the reference in header and page number in footer can match the chapter information, and tahe TOC can be updated correctly.

Then, after the successful merge, I will open the merged document and copy the information from other documents into the missing chapter of the document manually.

[in1.docx](https://github.com/aspose-free-consulting/projects/files/12064092/in1.docx)
[in2.docx](https://github.com/aspose-free-consulting/projects/files/12064093/in2.docx)

Thanks!

**Comment by PH8919** [comment] 2023-07-18 00:38
@AlexNosk 
Yes, my output target should be docx document and the information in header and footer should match with the chapter information.

Thanks

**Comment by AlexNosk** [comment] 2023-07-19 06:09
@PH8919 Thank you for additional information. As I have mentioned I am unable to achieve whet is required even using MS Word. As it is seen on the provided screenshot, MS Word improperly shows chapter number in the document's footer.

**Comment by PH8919** [comment] 2023-07-19 06:13
@AlexNosk 
Okay, I get it.
Thansk for your hard support and I will discuss with others about the issue. Thanks again!

**Comment by PH8919** [comment] 2023-08-01 11:15
@AlexNosk 
I found a way set discontinuous chapter number by "right click on the chapter number -> Continue from previous list-> Advanced value(skip numbers)" in MS Office, like what is shown in [your figure](https://github.com/aspose-free-consulting/projects/issues/326#issuecomment-1624810961). But when I export the PDF, the hidden chapter numbers appear in outline. Could you help to check it?

Thanks!

**Comment by AlexNosk** [comment] 2023-08-02 04:40
@PH8919 Could you please attach your input DOCX and output PDF documents here for testing? This will really simplify the issue analysis.

**Comment by PH8919** [comment] 2023-08-04 01:40
@AlexNosk 
Have you cheched the issue with my attachement?
If you can't support it currently, do you have further plan?

About the permanent license with several years of update and hotfix, is there a way to provide it?

Hope for your reply!
Thanks!

**Comment by AlexNosk** [comment] 2023-08-05 04:17
@PH8919 Excuse me for a late response, I am on vacation till 15th of August.

1. Aspose.Words mimics MS Word behavior when shows hidden numbers in the outlines. If you convert your document to PDF using MS Word you will get exactly the same result:  
[ms.pdf](https://github.com/aspose-free-consulting/projects/files/12266080/ms.pdf)
[out.pdf](https://github.com/aspose-free-consulting/projects/files/12266081/out.pdf)

2. I have managed to reproduce the problem with incorrect page numbers in the TOC.  The problem has been logged into our defect tracking system as **WORDSNET-25766**.

3. You should consult regarding the licensing models with our sales team in [Aspose.Purchase](https://forum.aspose.com/c/purchase/6) forum. My colleagues will help you shortly.

**Comment by PH8919** [comment] 2023-08-08 06:07
@AlexNosk  Sorry to disturb you.

1. Is it possible to support it in your product? I think DOCX and PDF are different data set, if PDF data set can support this feature, it will be possible to implement it.

Have a nice vacation!
Thanks!

**Comment by AlexNosk** [comment] 2023-08-15 05:57
@AlexNosk  Unfortunately, we cannot change behavior of Aspose.Words so that it does not match MS Word behavior since this might affect a lot of our existing customers.

**Comment by PH8919** [comment] 2023-08-15 07:25
> @PH8919 Thank you for additional information. I have tested your documents and it looks it is not possible to achieve what you need even in MS Word. I have merged your documents and specified list item value to 9, but page number does not have proper value: ![image](https://user-images.githubusercontent.com/31235892/253974674-99636ed2-539e-4c15-a66c-320eaad7aff1.png)
> 
> What is your output target format? Do you need to get the output as DOCX?



> @PH8919 Thank you for additional information. As I have mentioned I am unable to achieve whet is required even using MS Word. As it is seen on the provided screenshot, MS Word improperly shows chapter number in the document's footer.

@AlexNosk 
Welcome you back~~~
Do you think the issue above is the defect of MS Office or anything else?
Or do you know other method to create DOCX including discontinuous chapter numbers using MS Office?

Thanks!

**Comment by AlexNosk** [comment] 2023-08-16 09:14
@PH8919 It looks like this a peculiarity of MS Word. Unfortunately, I do not see other way to include chapter number. As a workaround you can use a separate section for each chapter and hardcode chapter number in the footer.

**Comment by PH8919** [comment] 2023-08-23 06:40
@AlexNosk we cannot use hardcode chapter or field(STYLEREF) in chapter number becuase the TOC won't be generated correctly, if we do it like that. So we want to find other available solutions.

Thanks

**Comment by AlexNosk** [comment] 2023-08-24 04:10
@PH8919 I am afraid, I do not see other possible workarounds of the issue right now.

**Comment by AlexNosk** [comment] 2023-09-06 12:31
@PH8919 The issue you have found earlies (**WORDSNET-25766**) has been resolved in the latest 23.9 version of Aspose.Words for Python:
<https://pypi.org/project/aspose-words/>

**Comment by PH8919** [comment] 2023-09-15 00:59
> @PH8919 The issue you have found earlier (**WORDSNET-25766**) has been resolved in the latest 23.9 version of Aspose.Words for Python: https://pypi.org/project/aspose-words/

Thanks for your efforts!
I will upgrade it and have a try.

**Closed** 2023-12-21 12:39 UTC

**Comment by PH8919** [comment] 2024-03-26 08:59
> @AlexNosk I append my DOCX and you can refer to it. it contains discontinuous chapters, 1, 3 and 6, the page number in each chapter is {chapter number}-{page number} My operation is:
> 
> 1. open the DOCX with aspose.words
> 2. update the fields
> 3. save the DOCX to be PDF.
> 
> `lic = aw.License() lic.set_license("Aspose.WordsforPythonvia.NET.lic") save_options = aw.saving.PdfSaveOptions() save_options.page_mode = aw.saving.PdfPageMode.USE_OUTLINES save_options.outline_options.headings_outline_levels = 9 doc = aw.Document("in.docx") doc.update_fields() doc.save("out.pdf",save_options)`
> 
> [in.docx](https://github.com/aspose-free-consulting/projects/files/12241386/in.docx)
> 
> Meanwhile, I find your all of your licneses just include one year of update and hotfix, Is there any way to buy a permanent license with several years of update and hotfix, like 3~5 years?
> 
> Thanks!

Hi @AlexNosk 
Sorry for late response and we have bought your product.
when i integrate it into my application, i found the page number in generated PDF cannot still match the DOCX. like, chapter number is 6, the page number should start from 6-1, but the generated PDF isnot that.

Please have a check!
PS: i cannot access your support site(https://[forum.aspose.com](https://forum.aspose.com/)/) due to some company policy currently so i hope let's discuss here.

**Comment by AlexNosk** [comment] 2024-03-26 11:17
@PH8919 I have rechecked with the latest version of Aspose.Words and as I can see PDF document is rendered the same way as in MS Word. Here is output PDF produced on my side: 
[out.pdf](https://github.com/aspose-free-consulting/projects/files/14757464/out.pdf)

If possible, could you please attach your problematic output PDF document here for our reference?

**Comment by PH8919** [comment] 2024-03-26 11:30
@AlexNosk 
It's a pity i cannot share you. i can describe it here. 
for chapter 1, the page number starts from 1-1, ---- Normal
for chapter 3, page number starts from 1-1, ---- Abnormal
for chapter 6, page number starts from 3-1. ---- Abnormal

Aspose.words = 24.3.0
My code is as follows:
`save_options = aw.saving.PdfSaveOptions()
        save_options.page_mode = aw.saving.PdfPageMode.USE_OUTLINES
        save_options.outline_options.headings_outline_levels = 9
        doc = aw.Document(outFile)
        doc.save(pdfFile, save_options)`

**Comment by AlexNosk** [comment] 2024-03-27 13:37
@PH8919 I have retested with your code and still the output looks correct on my side. Here is the output document produced using the following code on my side:
```py
save_options = aw.saving.PdfSaveOptions()
save_options.page_mode = aw.saving.PdfPageMode.USE_OUTLINES 
save_options.outline_options.headings_outline_levels = 9 

doc = aw.Document("C:\\Temp\\in.docx") 
doc.save("C:\\Temp\\out.pdf", save_options)
```
[out.pdf](https://github.com/aspose-free-consulting/projects/files/14774068/out.pdf)
