### ISSUE TITLE
Is it possible to update an excel stored at online location using aspose cells

### ISSUE THREAD

**Issue by amitklathwal** [aspose-free-consulting/projects#80] opened 2020-09-25 07:54 UTC
Hi,

I'm planning to use aspose cell to update and read values from an excel. I have my excel file in AWS S3 bucket and I plan to do this using a serverless architecture (AWS Lambda). Will it be possible to update and read excel file from S3 from lambda web api.
I'm using .NET Core serverless application.

Thanks!

**Comment by amjad-sahi** [comment] 2020-09-25 12:35
Aspose.Cells for .NET can be used on any environment where .NET runtime is installed. We did test Aspose.Cells with “AWS Serverless” project and it worked. You can read/write Excel files on AWS Lambda platform. But you got to follow certain usage rules on AWS Lambda (please note, no restriction is enforced by Aspose.Cells by any means).  See the Aspose APIs forum threads for your reference:
https://forum.aspose.com/t/i-want-to-generate-excel-file-and-convert-excel-file-to-pdf-by-using-aspose-cells/212994
https://forum.aspose.com/t/aspose-cells-in-aws-lambda-net-core-2-1-function-exception-when-saving-to-pdf/202354

Should you have any issue or queries in your implementation, you may post your issue with details and resource files in Aspose.Cells [forum](https://forum.aspose.com/c/cells/9).

**Comment by amitklathwal** [comment] 2020-09-28 10:54
Hey,

I'm using below code to fill excel cells where spreadSheetPath is a path to my local directory. Now I want to deploy my Web API as serverless application. For that I am keeping my excel file in S3. I am not sure how to fill values in excel in case of S3 as their is no local directory when we go serverless.

Can you please share an example where we are doing something like this

using (Workbook workbook = new Workbook(spreadSheetPath))
            {
                for (int i = 0; i < workbook.Worksheets.Count; i++)
                {
                    var sheet = workbook.Worksheets[i];
                    if (sheet != null)
                    {
                        var sheetItems = mapperList.Where(fx => fx.SheetName == sheet.Name);
                        foreach (var input in sheetItems)
                        {
                            sheet.Cells[input.Column + input.Cell].PutValue(input.DbVal, true);
                        }
                    }
                }
                workbook.Save(spreadSheetPath);
            }

**Comment by amjad-sahi** [comment] 2020-09-28 11:49
You should refer to the threads we suggested (above) in our previous reply, we also attached sample project in the threads. If you still find issue or queries, you may post your issue with details and resource files in Aspose.Cells [forum](https://forum.aspose.com/c/cells/9).

**Comment by amitklathwal** [comment] 2020-09-28 12:08
I am unable to access the samples. it says `Sorry, this file is private. Only visible to topic owner and staff members.`

**Comment by amjad-sahi** [comment] 2020-09-28 17:49
Please download the [sample](https://drive.google.com/file/d/1CJNJCyNAySlDk9ePRgBILYt-cQhUs434/view?usp=sharing) here for your reference. 

_Please note, we found some difficulties while implementing and these issues were really caused by some usage rules on AWS Lambda itself. Please note, it is hard to explain in one simple statement. Please check the attachment, we have also written some details on the usage and findings while working on the test project. Hopefully the sample with “readme.txt” will be helpful to you for your scenario as well_.

**Comment by shahzad-latif** [comment] 2020-11-12 12:37
Ref. This needs further investigation with respect to AWS Lambda environment.

**Comment by shahzad-latif** [comment] 2020-11-25 07:51
@amitklathwal 

Please post this query in our [free support forums](https://forum.aspose.com). As this matter needs further investigation and forums is the right place to log, track, and follow up properly. I'll close this thread. Thanks for your cooperation.

**Closed by shahzad-latif** 2020-11-25 07:51 UTC
Labels: Consulting Project, Follow Up, Investigation
