### ISSUE TITLE
PPT to PPTX conversion changes the playsettings of audio and vedio

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#202] opened 2022-04-28 05:48 UTC
PPT to PPTX conversion changes the playsettings of audio and vedio
![image](https://user-images.githubusercontent.com/49870259/165685480-2dc65c77-33db-4f81-9dd1-678cf13f0c69.png)
**Code：**
string src = "C:\test.ppt";
string dst = "C:\test.pptx";
Aspose.Slides.Presentation presentation = new Aspose.Slides.Presentation(src);
presentation.Save(dst, Aspose.Slides.Export.SaveFormat.Pptx);
[test.zip](https://github.com/aspose-free-consulting/projects/files/8579863/test.zip)
**Audio**  
![image](https://user-images.githubusercontent.com/49870259/165685261-866700ff-feac-4da3-8da7-0b722f107703.png)
![image](https://user-images.githubusercontent.com/49870259/165685273-dbc5eda8-ec6e-40ce-965e-f4a40aee3991.png)
**Video**
![image](https://user-images.githubusercontent.com/49870259/165685346-c5b4adbc-5e61-4ea8-96d1-e9624b55a5a8.png)
![image](https://user-images.githubusercontent.com/49870259/165685379-0e1694e2-124f-4e6b-935c-aed413c86da8.png)

**Comment by andreypotapovaspose** [comment] 2022-04-28 11:28
@MiniCassie,
Thank you for reporting the issue.

I've reproduced the problem with the audio and video options when converting PPT to PPTX and added a ticket with ID **SLIDESNET-43185** to our issue tracking system. Our development team will investigate this case. You will be notified when the issue is resolved.

**Comment by andreypotapovaspose** [comment] 2022-12-20 07:06
@MiniCassie,
The issue you found earlier (filed as SLIDESNET-43185) have been fixed in Aspose.Slides for .NET 22.7.
You can find the latest version of our library on the [Product Download](https://releases.aspose.com/slides/net/) page.

**Closed by andreypotapovaspose** 2022-12-20 07:06 UTC
