### ISSUE TITLE
I want to split a PPT and merge back in one file

### ISSUE THREAD

**Issue by albandum** [aspose-free-consulting/projects#59] opened 2020-07-14 10:21 UTC
Hello, 

I'm working on a project and trying to : 
- Upload a ppt file, split it in as many files as there are slides. 
- Pick a few of those slides and merge them back into one PPT that I can then download back.

Operation system : Mac OS 10.15
Stack : Rails 6

Is there anything else you need in the description ? 
Thanks a lot !

PS : I tried to do it with that https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/master/Plugins/Aspose_Slides_Java_for_Ruby/lib/asposeslidesjava/Slides/accessslides.rb but it just opens a Java 'bin' and freezes when I try to import the jar file. Nothing happens. So I'm open to both cloud or Java solutions, but I guess I would prefer the Java for Ruby method that might be faster and run on my own server.

**Comment by shahzad-latif** [comment] 2020-07-14 11:52
@albandum 

It looks like you're doing this in Ruby, so we'll prepare a sample project accordingly and share with you soon. Could you please share your input file as well, so we can try with the real data, if feasible? 

@asadalikhan90 Please have a look into this.

**Comment by albandum** [comment] 2020-07-14 11:55
Thanks ! 
There's no "real data", my goal is to be able to do that with any ppt provided, so you can pick any of yours !

**Comment by shahzad-latif** [comment] 2020-07-14 11:56
@albandum 

Great. Thanks for the confirmation. We'll do that.

**Comment by mudassirfayyaz** [comment] 2020-07-14 12:29
@albandum ,

Will it be helpful to you if we offer a Java console based solution to you which will  take a presentation and then create individual presentation files based on every single slide. Then give you provision to select any group of desired slide in any order and merge them to form a new presentation.

**Comment by albandum** [comment] 2020-07-14 14:47
@ mudassirfayyaz I've seen the Java based solution which I'd love to try as well but I'm facing issues you can find here : https://forum.aspose.com/t/exceptionininitializererror-in-aspose-java-for-ruby/215738

Thanks!

**Comment by mudassirfayyaz** [comment] 2020-07-14 21:47
@albandum ,

We will  get back to you with a solution as soon as possible. In mean while, I suggest you to please also explore our prepared [Github examples in for Ryby plugin using Aspose.Slides for Java](https://github.com/aspose-slides/Aspose.Slides-for-Java/tree/master/Plugins/Aspose_Slides_Java_for_Ruby). [This is the precise example link](https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/master/Plugins/Aspose_Slides_Java_for_Ruby/lib/asposeslidesjava/Slides/cloneslides.rb) that will be used to fulfill your requirements.

**Comment by albandum** [comment] 2020-07-15 08:26
@mudassirfayyaz thanks for the link ! That example is perfect but I'm still getting the bin freezing on import. 
Is there a version limit regarding java to be able to import the jar ? SDK or runtime version maybe ?
Thanks a lot.

**Comment by mudassirfayyaz** [comment] 2020-07-15 22:18
@albandum ,

You can please visit this documentation link for your convenience which entails the requirement for Aspose.Slides for Java integration with Ruby using RJB (Ruby Java Bridge). The following commands will be useful to you in executing the script.

require 'rjb'
Rjb::add_jar( Dir.glob("#{Rails.root}/lib/jars/*.jar").join(':'))
Rjb::load(Dir.glob("#{Rails.root}/lib/jars/*.jar").join(':'))

```
require 'rjb'
Rjb::add_jar('C:\Ruby27-x64\lib\ruby\gems\2.7.0\gems\asposeslidesjava-0.0.2\lib\jars\aspose-slides-20.6-jdk16.jar')
Rjb::load('C:\Ruby27-x64\lib\ruby\gems\2.7.0\gems\asposeslidesjava-0.0.2\lib\jars\aspose-slides-20.6-jdk16.jar')

require 'C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/asposeslidesjava-0.0.2/lib/asposeslidesjava'

include Asposeslidesjava
include Asposeslidesjava::HelloWorld
initialize_aspose_slides
```

**Comment by mudassirfayyaz** [comment] 2020-07-16 21:11
@albandum 

We have made a sample application that will help you in splitting the slides inside the presentation to individual presentations and then combining the individual presentations again to form a merged presentation. I have attached a complete document for setting up environment and using the application. Please proceed to [this link](https://drive.google.com/file/d/1-gTWx8hjay3iyS14-xIVviZ5dPwKhhk3/view?usp=sharing) for downloading the package.

**Comment by albandum** [comment] 2020-07-24 11:57
Hi @mudassirfayyaz , thanks a lot. This is moving forward :) 
I'm getting this error now : 
`W, [2020-07-24T13:40:20.118738 #65139]  WARN -- : Using the non licensed aspose jar. Please specify path to your aspose license directory in config/aspose.yml file!`

I've tried adding this in the rails app config dir as well as in the aspose.yml found in the gem dir, but still getting the same error : 

```
jar_dir: ../lib/aspose/jar
license_path: ../lib/aspose/license.lic
jvm_args: -Xms512m -Xmx1G

Am I doing something wrong ?
```

**Comment by albandum** [comment] 2020-07-24 12:03
Looks like this might be linked to a typo here : https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/master/Plugins/Aspose_Slides_Java_for_Ruby/lib/asposeslidesjava.rb#L68

**Comment by albandum** [comment] 2020-07-24 12:37
I've downloaded the gem and modified it locally to load the right licence file, but now I get : 

```
SEARCHING LICENSE PATH /Users/alban/Development/deckmatic/lib/aspose/license.lic
E, [2020-07-24T14:35:52.145834 #66319] ERROR -- : Could not load the license file : com.aspose.api.License
```

This is the code I'm using to load the licence, and the path is the right one. 

```
def load_aspose_license(aspose_license_path)
    puts "SEARCHING LICENSE PATH #{aspose_license_path}"
    if aspose_license_path && File.exist?(aspose_license_path)
      set_license(File.join(aspose_license_path))
    else
      [...]
```

Without documentation it's hard to know what to do next, what could be wrong with my temp licence I just ordered today ?

**Comment by albandum** [comment] 2020-07-24 12:43
Found it. 
Something you might want to be aware of, there are a lot of copy/paste typos in the asposeslides gem.
Here : 
https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/master/Plugins/Aspose_Slides_Java_for_Ruby/lib/asposeslidesjava.rb#L68
And Here : https://github.com/aspose-slides/Aspose.Slides-for-Java/blob/master/Plugins/Aspose_Slides_Java_for_Ruby/lib/asposeslidesjava.rb#L57

For example, so the gem is unusable if you don't have Aspose.Total loaded (because it's using cells and api jars instead of only Slides)

Looks like I'm making progression. I'll come back here if needed, thanks !

**Comment by mudassirfayyaz** [comment] 2020-07-24 16:20
@albandum ,

It's good to know that you are making progress. Please share with us if you need any support in terms of using API features on your end.

**Comment by albandum** [comment] 2020-07-25 11:52
Got it working. 
Two questions arose : 

- I'm getting these types of messages : 2020-07-25 13:43:18.941 ruby[69989:1043500] CoreText note: Client requested name ".SFNS-Bold", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
Is that because I'm on a mac ? Have you had these messages ?

- Also when splitting, it's giving me back a different format than the original PPT file. (4/3 instead of 16/9 I believe). Is there a way to keep the same format ? 

Thanks !

**Comment by mudassirfayyaz** [comment] 2020-07-25 21:29
@albandum ,

> I'm getting these types of messages :
2020-07-25 13:43:18.941 ruby[69989:1043500] CoreText note: Client requested name ".SFNS-Bold", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
Is that because I'm on a mac ? Have you had these messages ?

This warning means that the fonts that has been used in presentation is not available on machine where you are working. Therefore, it will be replaced by default Times New Roman font.

> Also when splitting, it's giving me back a different format than the original PPT file. (4/3 instead of 16/9 I believe). Is there a way to keep the same format ?

You can try using following code snippet in your application for setting the  presentation size
# Setting the slide size of new presentation
# setSize([SlideSizeType](https://apireference.aspose.com/slides/java/com.aspose.slides/SlideSizeType), [SlideSizeScaleType](https://apireference.aspose.com/slides/java/com.aspose.slides/SlideSizeScaleType))
target.getSlideSize().setSize(14, 1);


> Also getting this error :

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.aspose.slides.ms.core.System.Drawing.imagecodecs.jpeg.oracle.OracleJpegImageReader (file:/Users/alban/Development/project/lib/aspose/jar/slides.jar) to field com.sun.imageio.plugins.jpeg.JPEGImageReader.colorSpaceCode
WARNING: Please consider reporting this to the maintainers of com.aspose.slides.ms.core.System.Drawing.imagecodecs.jpeg.oracle.OracleJpegImageReader
Is this something I can fix or is that on your side ?

Is it a warning or error on your end. Can you please explain that what you are trying to do and getting this issue. Please share the used sample code along with source presentation reproducing it.

**Comment by albandum** [comment] 2020-07-28 10:04
Ok, thanks a lot ! Understood for the font, and thanks for the size, it works.

For the images I'm still investigating, I'll come back to you with more information later. 
I have another issue : I can only get aspose slides to work on one computer. On another one I get this error : 

`2.6.5 :015 > include Asposeslidesjava::SplitAndMerge.split_slides('test-10slides.pptx')
Traceback (most recent call last):
ExceptionInInitializerError (unknown exception)`

I have almost the same versions of Java on both, with a few differences. Only one of them seems to have the 1.6 JDK installed though. Is having 1.6 necessary ? I can't find much info about required java versions for Apose slides. Thanks !

**Comment by mudassirfayyaz** [comment] 2020-07-28 15:31
> 2.6.5 :015 > include Asposeslidesjava::SplitAndMerge.split_slides('test-10slides.pptx') Traceback (most recent call last): ExceptionInInitializerError (unknown exception)
> 
> I have almost the same versions of Java on both, with a few differences. Only one of them seems to have the 1.6 JDK installed though. Is having 1.6 necessary ? I can't find much info about required java versions for Apose slides. Thanks !
> 

You need to have JDK 1.6 or above installed on your machine. Since on machine you are able to execute the things properly. You can analyze more keenly to observe the difference of configurations on two machine to find the root cause.

**Comment by albandum** [comment] 2020-07-30 10:57
Hi, 

I'm now trying through Docker to make sure it will work on any machine. 
I'm installing ruby 2.6.6 and openjdk-11 

But when running Rjb::add_jar(jar_file) I'm getting this error : 
i```
rb(main):005:0> Rjb::add_jar(jar_file)
Traceback (most recent call last):
        2: from (irb):5
        1: from (irb):5:in `add_jar'
RuntimeError (Constants DL and Fiddle is not defined.)
```

I'm pretty sure this is a version issue. You're talking about JDK 1.6, when OpenJDK is at version 12. Do you require the proprietary Oracle JDK ? Or am I missing something ?

Thanks !

**Comment by shahzad-latif** [comment] 2020-08-11 08:25
@albandum 

The best place to get help and support with respect to [Aspose API is our free support forums](https://forum.aspose.com). This place is reserved for free consulting projects. So please post any future feature or issue requests in the forums for a quick and timely response.

**Closed** 2020-11-12 11:03 UTC
Labels: Forum Support
