### ISSUE TITLE
PPT to PPTX conversion changes Format background.

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#203] opened 2022-04-28 06:22 UTC
Code：
string src = "C:\test.ppt";
string dst = "C:\test.pptx";
Aspose.Slides.Presentation presentation = new Aspose.Slides.Presentation(src);
presentation.Save(dst, Aspose.Slides.Export.SaveFormat.Pptx);
**The document was created with WPS Office**
①
[test.zip](https://github.com/aspose-free-consulting/projects/files/8580043/test.zip)
**PPT Format background---Pattern fill**
![image](https://user-images.githubusercontent.com/49870259/165689806-302c3e3b-5962-4140-b29b-e242623d559c.png)
**PPTX Format background---Picture or texture fill**
![image](https://user-images.githubusercontent.com/49870259/165689857-4e7b00f0-c25d-4728-80fe-3e4e3e5f3150.png)
②meanwhile，if it has slide master，after conversion ,Slide Format background will Conver to Slide Master Format background
[test.zip](https://github.com/aspose-free-consulting/projects/files/8581107/test.zip)
![image](https://user-images.githubusercontent.com/49870259/165714453-807c1a68-7081-43c5-9a6a-fb9b8fe76920.png)
![image](https://user-images.githubusercontent.com/49870259/165714503-83de01fa-aa47-4293-8ec0-d2efd51919f6.png)
![image](https://user-images.githubusercontent.com/49870259/165714554-b4c425a1-1d90-4a56-9a69-0ec30b616214.png)

**Comment by andreypotapovaspose** [comment] 2022-04-28 13:57
@MiniCassie,
Thank you for reporting the issue.

I've reproduced the problem with the Format Background when converting the presentations to PPTX format and added a ticket with ID **SLIDESNET-43186** to our issue tracking system. Our development team will investigate this case. You will be notified when the issue is resolved.

**Comment by andreypotapovaspose** [comment] 2022-12-20 07:06
@MiniCassie,
The issue you found earlier (filed as SLIDESNET-43186) have been fixed in Aspose.Slides for .NET 22.7.
You can find the latest version of our library on the [Product Download](https://releases.aspose.com/slides/net/) page.

**Closed by andreypotapovaspose** 2022-12-20 07:06 UTC
