### ISSUE TITLE
I need to create an app to convert ppt to pptx，I've used this tool but doesn't convert shape name correctly

### ISSUE THREAD

**Issue by MiniCassie** [aspose-free-consulting/projects#166] opened 2022-01-05 09:27 UTC
![image](https://user-images.githubusercontent.com/49870259/148193745-966b586d-5c71-479c-a6ed-2e044d4d87af.png)

![image](https://user-images.githubusercontent.com/49870259/148193771-fcc25e0a-ca18-4c2b-ae69-ad8edcd5abb9.png)

**Comment by andreypotapovaspose** [comment] 2022-01-05 10:50
@MiniCassie,
Thank you for the inquiry.

Unfortunately, I was unable to understand the problem on your screenshots. Please describe the problem in more detail on [Aspose.Slides forum](https://forum.aspose.com/c/slides/) or [here](https://forum.aspose.com/c/chinese/) and share the following:

- input PPT file
- output PPTX file
- code example that reproduces the problem

**Comment by MiniCassie** [comment] 2022-01-06 01:17
**input PPT file and output PPTX file**
[Test.zip](https://github.com/aspose-free-consulting/projects/files/7818719/Test.zip)
**code example that reproduces the problem(C#)**
   string src = "C:\\Test.ppt";
   string dst = "C:\\Test.pptx";
   AsposePpt.Presentation presentation = new AsposePpt.Presentation(src);
   presentation.Save(dst, AsposePpt.Export.SaveFormat.Pptx);
**problem**
In the PPT file,shape name is "WordArt 5".But in the  PPTX file,shape name is " 5124"
![image](https://user-images.githubusercontent.com/49870259/148312465-6e9e21d3-fcd4-4a80-ba4f-8469ca991b59.png)
![image](https://user-images.githubusercontent.com/49870259/148312525-90f40e69-40a3-44fa-8c39-0d917544b84b.png)

**Comment by andreypotapovaspose** [comment] 2022-01-06 09:19
@MiniCassie,
Thank you for the additional information.

I've reproduced the problem with the shape name after conversion to PPTX format. This is a bug. I've added a ticket with ID **SLIDESNET-42990** in our issue tracking system. Our development team will investigate this case. You will be notified when the issue is resolved.

**Comment by andreypotapovaspose** [comment] 2022-02-14 08:07
@MiniCassie,
The issue you have found earlier (filed as SLIDESNET-42990) has been fixed. The fix will be included in Aspose.Slides 22.2. This release will be [published](https://downloads.aspose.com/slides/net) in the second half of February.

**Comment by MiniCassie** [comment] 2022-03-01 03:38
Unfortunately,the issue has not been fixed.	Sometimes,Shape name is still changed while converting PPT to PPTX .May be it is related to file.
[Uploading test.zip…]()
![image](https://user-images.githubusercontent.com/49870259/156100240-05bb6471-0031-41a1-9510-3653703fb699.png)

**Closed** 2022-03-01 08:20 UTC
