### ISSUE TITLE
Unable to generate proper parent-child hierarchy JSON structure while converting Excel to JSON and vice versa.

### ISSUE THREAD

**Issue by sudipmahato90** [aspose-free-consulting/projects#261] opened 2022-11-04 14:52 UTC
As part of our project, we have a requirement to convert Excel Data to JSON as well as JSON Data to Excel.
We are able to generate in the required format using aspose, only for flat data's.

**Issue** :  Our json Data contains min 2 level and max 5 level of parent-child row. We wanted to convert those Data to a proper Excel. Similarly the same Excel Data to render in the similar json format, whereas the generated json in ASPOSE is flat it is not as per the expected parent-child json format.

If you can get some help that would be gratefully for us.

**Comment by amjad-sahi** [comment] 2022-11-05 09:24
@sudipmahato90, 

Could  you please provide the following artifacts and resource files to investigate your issue/requirements:
1) JSON data (containing some levels of parent-child).
2) Sample (runnable) code that you are using via Aspose.Cells to import JSON data to Excel.
3) Current output (undesired) Excel file via Aspose.Cells.
4) Your expected Excel file, you may generate your desired Excel file (based on your JSON data) in MS Excel manually.
(PS. please zip the files prior attaching here.)

We also encourage you to post your queries or issue in the dedicated [forum](https://forum.aspose.com/c/cells/9), we handle clients queries/issue(s) efficiently there.

**Comment by sudipmahato90** [comment] 2022-11-07 12:58
1.JSON data (containing some levels of parent-child).
Ans:Sample_json.json(Extract the folder and follow the path AsposeConversion\AllFile).

2.Sample (runnable) code that you are using via Aspose.Cells to import JSON data to Excel.
Answer: Please extract the project AsposeConversion folder.

3.Current output (undesired) Excel file via Aspose.Cells.
Ans:Sample_excel__Output20221107121936.xls(1sheet).

4.Your expected Excel file, you may generate your desired Excel file (based on your JSON data) in MS Excel manually.
Ans: Sample_excel__Output20221107121936 (2nd sheet).

Also Vice versa is required i.e when we convert Excel(SampleExcel_Input.xls) To Json the generated output is in Flat data format using aspose (ExcelToJson_Output20221107123939).
We except same parent-child hierarchy JSON structure while converting Excel to JSON.(i.e-Sample_json.json)
Please find the attached sample code with read me file (Readme.txt )
[AsposeConversion.zip](https://github.com/aspose-free-consulting/projects/files/9951755/AsposeConversion.zip)

**Comment by amjad-sahi** [comment] 2022-11-07 15:11
@sudipmahato90,

Thanks for the resource files and sample application.

I tested your scenario/case using your sample files. It looks like Aspose.Cells can import/render JSON to Excel and vice versa for flat data only. I am able to reproduce the issue as you mentioned by using your sample project and sample files. The API could not generate parent-child hierarchy JSON structure while converting Excel to JSON and vice versa. I have logged a ticket with an id "CELLSNET-52242" for your issue.  We will investigate and look into the details of your requirements/issue. 

Once we have an update on it, we will let you know.

**Comment by sudipmahato90** [comment] 2022-11-09 07:23
Hi Team, 
Did you get a chance to look into the issue.
If you can get some help that would be gratefully for us.

**Comment by amjad-sahi** [comment] 2022-11-09 09:33
@sudipmahato90,

Since we just logged the ticket a couple of days ago, so kindly spare a little time (5-7 days or so) to evaluate your issue/requirements in details. Then we might be able to update you on it.

Once we have any new information available, we will update you.

**Comment by amjad-sahi** [comment] 2022-11-14 10:47
@sudipmahato90,

1) For JSON to Excel
If you want to title "Scenerios" as "BaseScenerio","LowScenerio","HighScenerio", please change your JSON data:
```
 "Scenerio": [
                        {
                            "Name": "BaseScenerio",
                            "Value": "200"
                        },
                        {
                            "Name": "LowScenerio",
                            "Value": "300"
                        },
                        {
                            "Name": "HighScenerio",
                            "Value": "300"
                        }
                    ],
```
as
```
"BaseScenerio": "200",
"LowScenerio":"300",
"HighScenerio": "300",
```

2) For Excel-to-JSON
We need more time to drill down the data to generate proper parent-child hierarchy JSON structure.  
Once we figure it out, we will update you.

**Comment by amjad-sahi** [comment] 2022-11-30 11:40
@sudipmahato90,

We are pleased to inform you that your issue has been resolved now. The fix will be included in our upcoming release (Aspose.Cells for .NET v22.12) which is scheduled in the first half of December 2022. You will be notified once the next release is published. Please refer to the sample code segment that you will use with the upcoming release:
e.g.
**Sample code:**
```cs
Workbook workbook = new Workbook(Constants.sourcePath + @"json\CellsNet52242.json");
JsonSaveOptions saveOptions = new JsonSaveOptions();
saveOptions.ExportNestedStructure = true;
workbook.Save(Constants.destPath + "CellsNet52242.json", saveOptions);
```

Keep in touch.

**Comment by amjad-sahi** [comment] 2022-12-12 08:16
@sudipmahato90,

Please try our latest version/fix: Aspose.Cells for .NET v22.12 ([Download](https://releases.aspose.com/cells/net/) | [NuGet](https://www.nuget.org/packages/Aspose.Cells/)). Your issue should be fixed in it.

Let us know if you still find any issue.

**Closed** 2023-06-14 04:05 UTC
