### ISSUE TITLE
AE_2_1_0002 NO LOGIN failed

### ISSUE THREAD

**Issue by developeririskpo** [aspose-free-consulting/projects#260] opened 2022-10-19 11:08 UTC
Hi Team

We are getting the above error (AE_2_1_0002 NO LOGIN failed) while reading the emails using imap. 

Product details - Aspose.Email.dll version number 17.7 (Email Id registered in Aspose account is admin@iriskpo.in)

This issue has started from October 11th 2022

Please find the code below

            Aspose.Email.License licenseEmail = new Aspose.Email.License();
            licenseEmail.SetLicense("Aspose.Email.lic");

            client.Host = "outlook.office365.com";
            client.Username = "documentssnap@irissnap.co.uk";
            client.Password = "*******";
            client.Port = 993;

            client.SecurityOptions = Aspose.Email.Clients.SecurityOptions.Auto;

            Aspose.Email.Clients.Imap.ImapQueryBuilder builder = new Aspose.Email.Clients.Imap.ImapQueryBuilder();
            builder.HasNoFlags(Aspose.Email.Clients.Imap.ImapMessageFlags.IsRead);
            Aspose.Email.Tools.Search.MailQuery query = builder.GetQuery();
            Aspose.Email.Clients.Imap.ImapMessageInfoCollection infoimap = client.ListMessages(query);

Please do the needful to rectify the error ASAP

Thanks

**Comment by developeririskpo** [comment] 2022-10-21 03:26
Hi

We have tried using the latest version also. That also not helped. Please find the below log and provide a solution asap.

— Aspose.Email for .NET 4.0 [22.9.0.0] IMAP Client diagnostic log
— Started: 20/10/2022 23:28:12
Imap client[1|20/10/2022 23:28:14]:
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Connect to: outlook.office365.com:993 SecurityOptions.SSLImplicit <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Environment version: 4.0.30319.42000 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OS version: Microsoft Windows NT 6.2.9200.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly title: Aspose.Email for .NET 4.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly version: 22.9.0.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]:
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap server[1|20/10/2022 23:28:14]: * OK The Microsoft Exchange IMAP4 service is ready. [TQBBADAAUABSADAAMQBDAEEAMAAxADAANwAuAEkATgBEAFAAUgBEADAAMQAuAFAAUgBPAEQALgBPAFUAVABMAE8ATwBLAC4AQwBPAE0A]
Imap server[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: AE_1_1_0000 CAPABILITY
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap server[1|20/10/2022 23:28:14]: * CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
Imap server[1|20/10/2022 23:28:14]: AE_1_1_0000 OK CAPABILITY completed.
Imap server[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap client[1|20/10/2022 23:28:14]: AE_1_1_0001 AUTHENTICATE PLAIN ************
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap server[1|20/10/2022 23:28:15]: AE_1_1_0001 NO AUTHENTICATE failed.
Imap server[1|20/10/2022 23:28:15]:
20/10/2022 23:28:15

Imap client[1|20/10/2022 23:28:15]: AE_1_1_0002 LOGIN documentssnap@irissnap.co.uk ************
Imap client[1|20/10/2022 23:28:15]:
20/10/2022 23:28:15

Imap server[1|20/10/2022 23:28:16]: AE_1_1_0002 NO LOGIN failed.
Imap server[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]:
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Connect to: outlook.office365.com:993 SecurityOptions.SSLExplicit <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Environment version: 4.0.30319.42000 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OS version: Microsoft Windows NT 6.2.9200.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly title: Aspose.Email for .NET 4.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly version: 22.9.0.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:16]:
Imap client[1|20/10/2022 23:28:16]:
20/10/2022 23:28:16

Imap client[1|20/10/2022 23:28:26]: The operation ‘ReadGreetingString’ terminated. Timeout ‘10000’ has been reached.
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: The operation ‘ReadGreetingString’ terminated. Timeout ‘10000’ has been reached.
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]:
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Connect to: outlook.office365.com:993 SecurityOptions.None <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Environment version: 4.0.30319.42000 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> OS version: Microsoft Windows NT 6.2.9200.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly title: Aspose.Email for .NET 4.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Assembly version: 22.9.0.0 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Imap client[1|20/10/2022 23:28:26]:
Imap client[1|20/10/2022 23:28:26]:
20/10/2022 23:28:26

Thanks

**Comment by tahir-manzoor** [comment] 2022-10-21 04:05
@developeririskpo 

We have logged this problem in our issue tracking system as **EMAILNET-40778**. You will be informed once this issue is resolved.

**Comment by tahir-manzoor** [comment] 2022-12-12 03:47
@developeririskpo 

The issue is on the server side. It's very possible it no longer supports Basic Authentication. The log file confirms this assumption.
Note the following lines:

```
Imap client[1|20/10/2022 23:28:14]: AE_1_1_0001 AUTHENTICATE PLAIN ************
Imap client[1|20/10/2022 23:28:14]:
20/10/2022 23:28:14

Imap server[1|20/10/2022 23:28:15]: AE_1_1_0001 NO AUTHENTICATE failed.
Imap server[1|20/10/2022 23:28:15]:
20/10/2022 23:28:15

```

Generally, Basic Authentication support is [discontinued](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online) by Microsoft.

You must switch to a Modern Authentication. First of all, you need to register the application on Azure Portal and configure the necessary options. Please read the following article:
[Connect to Microsoft365 Mailbox using Modern Authentication in C# .NET](https://blog.aspose.com/2022/06/14/connect-to-microsoft365-mailbox-using-modern-authentication-in-c-.net/).

**Closed** 2023-06-14 04:03 UTC
